---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver_config:
      network:
      - ["forwarded_port", {guest: 8080, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[gogs::default]
    attributes:
